### PR TITLE
Dev amy

### PR DESCRIPTION
**Pull request by amyheather**

### CODE REVIEW

**Comment by TomMonks** [comment]
This is excellent work! Well done.  My review below. I think this is everything (although I did manage to lose my original review when typing directly into the comments section!)

## Changes required

* LICENSE: update from "Tom Monks" to "STARS Project Team".
* MODEL IMAGE: Showing what can be modified was a good idea! I wonder if the image needs to be this big though? Could we also have the model recap image collapsed by default as it means the simulated button is not visible immediatley on some screens.
* ARRIVALS PROFILE: One major update planned is to allow users to upload new arrival profiles. This requires a modification to the `treat-sim` class `Scenario`.  Once upload we want the user to be able to view the profile (to sense check it). I wonder if you can keep it on the interactive page for now.  One option would be to use tabs.
* RESULTS LABELS: your effort is better than mine.  But please update to include units. Recently a clinician complained that I had not included units in the results table (i.e mins).  If useful there's an option to import `RESULTS_LABELS` from `treat-sim` https://github.com/pythonhealthdatascience/stars-treat-sim/blob/main/treat_sim/model.py
* ENV: good work finding ways to consistently download and copy/paste.  Please remove the redundant bokeh and bokeh events packages from `reqiurements.txt` and `environment.yml` (this is a good simplification)
* CHANGES: adopt the standard format you found and used in `treat-sim`
* ABOUT: add MRC funding number
* ABOUT change:

> Note: The model presented here is part of STARS version 1.0: independent research supported by the National Institute for Health Research Applied Research Collaboration South West Peninsula. The views expressed in this publication are those of the author(s) and not necessarily those of the National Institute for Health Research or the Department of Health and Social Care.

To


> Note: This model is part of the ongoing STARS 2.0 study. An early version of the model presented here was part of STARS version 1.0: independent research supported by the National Institute for Health Research Applied Research Collaboration South West Peninsula. The views expressed in this publication are those of the author(s) and not necessarily those of the National Institute for Health Research or the Department of Health and Social Care.

## Commit style

I haven't thought about this, but we should get a standardish commit style between us.  I always use  a `SUBJECT: short msg` format where subject might be ENV, FEAT, FIX/PATCH, etc.  Some info is here. https://www.conventionalcommits.org/en/v1.0.0/  BREAKING CHANGE seems important.  What you have done is fine, just thinking about going forward and across repos.

**Comment by TomMonks** [comment]
ARCHIVE: we can remove it.  All legacy code is easily accessible via GitHub releases.

**Comment by TomMonks** [comment]
README: It currently doesn't link to the "towards paper".  let's ask people to cite that as well if they use the app.
README: add Amy Heather ORCID badge

**Comment by amyheather** [comment]
@TomMonks for you to review. All changes implemented except "ARRIVALS PROFILE" as assuming that's a future change and nothing currently to modify (but do correct me if I'm wrong). However, can add it to GitHub issues as enhancement?

FYI. RE: tabs, the latest streamlit version (1.35.0) introduced tabs with `st.tabs()` which could be good for that when needed. I think that's likely the best option, but prior to that feature being introduced, [when I needed to make tabs on Kailo](https://github.com/kailo-beewell/synthetic_northern_devon_dashboard_stable_release/blob/main/pages/1_Standard%20survey.py), I made tabs using a combination of the session state, `st.buttons()` and `st.rerun()` to toggle page content between a few options - example:

```
# Set default page
if 'standard_page' not in st.session_state:
    st.session_state.standard_page = 'area'

# Set button text weight depending on current choice
if st.session_state.standard_page == 'area':
    btn_area_txt = '**By area**'
    btn_char_txt = 'By pupil characteristics'
elif st.session_state.standard_page == 'char':
    btn_area_txt = 'By area'
    btn_char_txt = '**By pupil characteristics**'

st.divider()
st.markdown(f'''
The standard #BeeWell survey was completed by
{school_counts['standard_pupils']} pupils in Years 8 and 10 at
{school_counts['standard_schools']} mainstream schools. You can view results
either:''')
cols = st.columns(2)
with cols[0]:
    if st.button(btn_area_txt, key='btn_area', use_container_width=True):
        st.session_state.standard_page = 'area'
        st.rerun()
with cols[1]:
    if st.button(btn_char_txt, key='btn_char', use_container_width=True):
        st.session_state.standard_page = 'char'
        st.rerun()
st.divider()
````

**Comment by TomMonks** [comment]
Thanks @amyheather

**Pull request merged**
